### Register a new user
POST https://e-commerce-api-heyc.onrender.com/auth/register
Content-Type: application/json

{
  "fullName": "Sani Jonathan",
  "email": "sanij667@gmail.com",
  "password": "123456",
  "role": "admin"
}

###

###  Login user
POST https://e-commerce-api-heyc.onrender.com/auth/login
Content-Type: application/json

{
  "email": "sanij667@gmail.com",
  "password": "123456"
}

##

###  Get all products
GET https://e-commerce-api-heyc.onrender.com/products
Accept: application/json

###

###  Add a product (Admin only)
POST https://e-commerce-api-heyc.onrender.com/products
Content-Type: application/json
Authorization: Bearer {{TOKEN_HERE}}

{
  "productName": "iPhone 15",
  "cost": 1200,
  "productImages": ["https://example.com/image.jpg"],
  "description": "Latest Apple phone",
  "stockStatus": "in-stock"
}

###

###  Delete a product (replace PRODUCT_ID)
DELETE https://e-commerce-api-heyc.onrender.com/products/<product_id>
Authorization: Bearer {{TOKEN_HERE}}

